### ISSUE TITLE
Failed building wheel for gensim

### ISSUE THREAD

**Issue by luqisha** [sagorbrur/bnaug#3]
I can't seem to install `bnaug` with `!pip install bnaug` in Google Colab using Python version 3.10.11. 

I am getting the following errors.

````
Building wheels for collected packages: gensim
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for gensim (setup.py) ... error
  ERROR: Failed building wheel for gensim
  Running setup.py clean for gensim
Failed to build gensim
Installing collected packages: tokenizers, sentencepiece, python-crfsuite, sklearn-crfsuite, huggingface-hub, gensim, transformers, bnlp-toolkit, bnaug
  Attempting uninstall: gensim
    Found existing installation: gensim 4.3.1
    Uninstalling gensim-4.3.1:
      Successfully uninstalled gensim-4.3.1
  error: subprocess-exited-with-error
  
  × Running setup.py install for gensim did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Running setup.py install for gensim ... error
  Rolling back uninstall of gensim
  Moving to /usr/local/lib/python3.10/dist-packages/gensim-4.3.1.dist-info/
   from /usr/local/lib/python3.10/dist-packages/~ensim-4.3.1.dist-info
  Moving to /usr/local/lib/python3.10/dist-packages/gensim/
   from /usr/local/lib/python3.10/dist-packages/~ensim
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> gensim

note: This is an issue with the package mentioned above, not pip.
````

**Comment by sagorbrur** [comment]
Hi @luqisha ,
Fixed the problem in patch release. Try the new version [1.1.1](https://github.com/sagorbrur/bnaug/releases/tag/1.1.1)

**Comment by luqisha** [comment]
Yes, the installation is working now.  But when I'm trying to use the `masking_based` Token Replacement, I am getting the following error. I used the demo code provided in the [Demo Notebook](https://github.com/sagorbrur/bnaug/blob/main/notebook/bnaug_demo.ipynb)

```
ModuleNotFoundError: No module named 'keras.saving.hdf5_format'

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py](https://localhost:8080/#) in _get_module(self, module_name)
   1076             return importlib.import_module("." + module_name, self.__name__)
   1077         except Exception as e:
-> 1078             raise RuntimeError(
   1079                 f"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its"
   1080                 f" traceback):\n{e}"

RuntimeError: Failed to import transformers.models.bert.modeling_tf_bert because of the following error (look up to see its traceback):
No module named 'keras.saving.hdf5_format'
```

Is this related to the previous error?

**Comment by sagorbrur** [comment]
It might be the Transformers version. This is different. 
I will regenerate the issue and try to fix it soon. 
Meanwhile, you can clone the repository and try with specific transformers version. 
I am hoping it will work then.

**Comment by ZubairAzimMiazi** [comment]
> Yes, the installation is working now. But when I'm trying to use the `masking_based` Token Replacement, I am getting the following error. I used the demo code provided in the [Demo Notebook](https://github.com/sagorbrur/bnaug/blob/main/notebook/bnaug_demo.ipynb)
> 
> ```
> ModuleNotFoundError: No module named 'keras.saving.hdf5_format'
> 
> The above exception was the direct cause of the following exception:
> 
> RuntimeError                              Traceback (most recent call last)
> [/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py](https://localhost:8080/#) in _get_module(self, module_name)
>    1076             return importlib.import_module("." + module_name, self.__name__)
>    1077         except Exception as e:
> -> 1078             raise RuntimeError(
>    1079                 f"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its"
>    1080                 f" traceback):\n{e}"
> 
> RuntimeError: Failed to import transformers.models.bert.modeling_tf_bert because of the following error (look up to see its traceback):
> No module named 'keras.saving.hdf5_format'
> ```
> 
> Is this related to the previous error?

@luqisha you can just "pip install --upgrade transformers". This worked for me.
